### ISSUE TITLE
Invalid replicateChain.call() params on branch 09-end

### ISSUE THREAD

**Issue by pcoterecollective** [SandraRodgers/Ask-AI#2]
In lesson 9,
`const firstResponse = await replicateChain.call({ input: req.body.prompt })` ([server.js, line 155](https://github.com/SandraRodgers/Ask-AI/blob/a159dca05b722addf7d83224433d5588a010feb3/server.js#L155C80-L155C80)) results in an error. 
According to the returned error, the `prompt` input property is required. 
Valid input parameter would then be
`const firstResponse = await replicateChain.call({ input: { prompt: req.body.prompt } })`

**Comment by SandraRodgers** [comment]
Hey @pcoterecollective!

I wasn't able to reproduce this error. If you checkout to the branch `09-end`,  you can try out the code and see what I mean. It contains the line `const firstResponse = await replicateChain.call({ input: req.body.prompt })`. And everything works. 

Were you able to get it working using your fix? I'm not able to reproduce the error and everything works fine, so I'll leave my code the way it is for now. Thanks for reaching out.
